### ISSUE TITLE
Clarification of state of plugin?

### ISSUE THREAD

**Issue by rreusser** [brentvatne/react-native-linear-gradient#40] opened 2015-11-19 18:24 UTC
We've been using 0.3.2 for a while and it's been great! Thanks soo much! Now working on the android transition and trying to figure out which version/branch/fork is the right one, but it's not really clear. The easy way:

```bash
$ npm install --save react-native-linear-gradient
react-native-linear-gradient@0.3.2 node_modules/react-native-linear-gradient
```

doesn't install 1.?.0-alpha, which appears to have android support but has not really been touched/merged in a month. Installing directly from nonspecific GH#master isn't really acceptable for production. Which is all totally fine, but is it possible to clarify what exists or needs to be done? Is it stable but you're not quite able to vouch for it in production? Are there outstanding issues? 1.0.0-alpha vs. 1.1.0-alpha?

Thanks!

**Comment by rreusser** [comment] 2015-11-19 18:49
Specifically, using 1.1.0-alpha, everything seems to work fine, just no gradients and not 100% sure where to go from here:

```jsx
<LinearGradient style={styles.imageOverlay} colors={['#f00','#0f0']}/>
```

iOS:
<img width="320" alt="ios" src="https://cloud.githubusercontent.com/assets/572717/11280411/fa19198a-8ec3-11e5-8788-badf652b42bf.png">

Android:
<img width="344" alt="android" src="https://cloud.githubusercontent.com/assets/572717/11280415/fe2ea904-8ec3-11e5-8af8-fa068187d121.png">

**Comment by brentvatne** [comment] 2015-11-19 20:36
cc @nickhudkins

**Comment by nickhudkins** [comment] 2015-11-19 20:51
Hey @rreusser, I haven't seen gradients not behaving in Android, but the last time I tested 1.1.0-alpha was directly after RN Android support landed. Which version of RN are you using here?

The reason it currently is in alpha is that there has simply not been enough testing done as far as the Android side goes.

Are you receiving any warnings? Do you have a simplified test case I could use? Otherwise I'll get a simple example going with 0.14.2 and see if I can reproduce.

**Comment by rreusser** [comment] 2015-11-19 20:59
Ah, sorry, I should have definitely mentioned… I'm using the 0.15-stable branch. (We figured riding the bleeding edge of android support was worth the effort since we've been developing iOS for two months and Android for three days, and based on past releases, 0.15.0 should land in a matter of… hours?)

No warnings, but I'll try a fresh project and see if that works. Or maybe just create a PR with the corresponding Android example.

**Comment by nickhudkins** [comment] 2015-11-19 21:25
Absolutely if you submit a PR I can pull it down and see if I can debug as well :+1:

**Comment by rreusser** [comment] 2015-11-19 21:26
Cool. I'll check this against 0.14.2 and 0.15.x and let you know! ETA: 1-2 days?

**Comment by nickhudkins** [comment] 2015-11-20 01:08
Hey @rreusser This is 0.15.0-rc running with 1.1.0-alpha


![Android](https://s3.amazonaws.com/f.cl.ly/items/2F0o072A2y3C3b2x1P1f/Screen%20Shot%202015-11-19%20at%208.07.07%20PM.png)

**Comment by rreusser** [comment] 2015-11-20 01:11
Interesting. I really appreciate the check. It helps a lot! It seems I must have something else going on then. No internet at the moment, but I'll give everything a very careful look and let you know how it goes. Thanks!!!

**Comment by rreusser** [comment] 2015-11-20 01:15
(Sorry if putting this on you is lazy! This is in a queue of like forty issues in the Android milestone, so trying to hammer through and locate any obvious blockers as quickly as possible!)

**Comment by nickhudkins** [comment] 2015-11-20 01:18
What version of Android are you looking to support? Perhaps the issue is there. I have also run this on 4.4.4 without trouble. Software is moving fast! Lots of stuff breaks and being that I'm the person who is responsible for 1.1.0-alpha, I probably am the person to answer the questions or fix the bugs :+1: 

If I had to take a wild guess, you may be missing

`import com.BV.LinearGradient.LinearGradientPackage;`

and

`.addPackage(new LinearGradientPackage())`

from your Main.java file.

**Comment by rreusser** [comment] 2015-11-20 17:18
Okay, since the example worked, I did some reductio ad absurdum and ended up with this:

1. rm -rf ./android
2. downgrade to 0.14.2
3. `./node_modules/.bin/react-native android`
4. `npm install --save react-native-linear-gradient@1.1.0-alpha`
5. upgrade to RN 0.15-stable

It now works. I looked through the diff with a fine-toothed comb but can't find anything substantial that's changed. I have no idea why it didn't work before and works now. But it works. I'll see what happens with a fresh project when 0.15.0 lands, but until then, I don't think there's anything to be done here. Close, I think.

**Closed** 2015-11-25 22:34 UTC
